export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES'

export const ADD_RECIPE = 'ADD_RECIPE'

export const ADD_MESSAGE = 'ADD_MESSAGE'

export const  SET_SIGNED_IN_USER = 'SET_SIGNED_IN_USER'

export const SET_PROFILE = 'SET_PROFILE'

export const SET_VISIT_PROFILE = 'SET_VISIT_PROFILE'

export const SET_FEED = 'SET_FEED'

export const ACCEPT_COLLAB_REQUEST_PENDING_BUSINESS = 'ACCEPT_COLLAB_REQUEST_PENDING_BUSINESS'

export const ACCEPT_COLLAB_REQUEST_PENDING_INFLUENCER = 'ACCEPT_COLLAB_REQUEST_PENDING_INFLUENCER'

export const SET_BUSINESS = 'SET_BUSINESS'

export const SET_INFLUENCER = 'SET_INFLUENCER'

export const SET_SEARCH = 'SET_SEARCH'

export const OPENED_CHAT = 'OPENED_CHAT'

export const CREATE_CHAT = 'CREATE_CHAT'

export const SET_CHAT_LIST = 'SET_CHAT_LIST'

export const SET_LAST_FIVE_MESSAGES = 'SET_LAST_FIVE_MESSAGES'

export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE'

export const SET_LOGIN_INFO = 'SET_LOGIN_INFO'

export const ACCEPT_COLLAB_REQUEST = 'ACCEPT_COLLAB_REQUEST'
